name: 'gradle-build'

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        java: [
            16    # Minimum supported by Minecraft
        ]
        distribution: ['adopt', 'zulu']
        os: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
    - name: Make gradle wrapper executable
      if: ${{ runner.os != 'Windows' }}
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload build artifacts
      # Only upload artifacts built from latest java on one OS
      if: ${{ runner.os == 'Linux' && matrix.java == '16' && matrix.distribution == 'adopt' }}
      uses: actions/upload-artifact@v1
      with:
        name: build-artifacts
        path: build/libs
